version: '2'
services:
  web:
    build: ./ipy
    ports:
      - "33322:8888"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./nb:/notebooks
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
